DROP TABLE IF EXISTS applicants CASCADE;

CREATE TABLE applicants (
  id SERIAL PRIMARY KEY NOT NULL,
  socialworker_id INTEGER REFERENCES socialworkers(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  isHoused BOOLEAN NOT NULL DEFAULT FALSE,
  address VARCHAR(255) NOT NULL,
  known_locations VARCHAR(255) NOT NULL,
  dependants VARCHAR(255) NOT NULL,
  resource_provided INTEGER REFERENCES resources(id) ON DELETE CASCADE,
  isFlagged BOOLEAN NOT NULL DEFAULT FALSE,
  applied_at DATE NOT NULL DEFAULT CURRENT_DATE,
  isActive BOOLEAN NOT NULL DEFAULT TRUE

);