DROP TABLE IF EXISTS clients CASCADE;

CREATE TABLE clients (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  isHoused BOOLEAN NOT NULL DEFAULT FALSE,
  address VARCHAR(255) NOT NULL,
  known_locations VARCHAR(255) NOT NULL,
  dependants VARCHAR(255) NOT NULL,
  resource_provided VARCHAR(255) NOT NULL,
  resource_requested TEXT REFERENCES resources(resource_type) ON DELETE CASCADE,
  applied_at DATE NOT NULL DEFAULT CURRENT_DATE,
  isActive BOOLEAN NOT NULL DEFAULT TRUE,
  status VARCHAR(255) NOT NULL
);