DROP TABLE IF EXISTS updates CASCADE;

CREATE TABLE updates (
  id SERIAL PRIMARY KEY NOT NULL,
  client_id INTEGER REFERENCES clients(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  date DATE NOT NULL
);